const { lines } = require('mrm-core');
const fetch = require('node-fetch');

async function gitignore() {
  const file = await fetch(
    'http://gitignore.io/api/node,linux,macos,windows,visualstudiocode',
  ).then((response) => response.text());

  const ignoreList = file
    .split('\n')
    .filter((line) => !!line && line.indexOf('#') !== 0);

  lines('.gitignore')
    .add('# Start generated by mrm rmr-gitignore')
    .add(ignoreList.concat('.idea/').sort())
    .add('# End generated by mrm rmr-gitignore')
    .save();
}

gitignore.description = 'Adds .gitignore';
module.exports = gitignore;
